# Generated by Django 5.2.13 on 2026-04-16 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('language', models.CharField(max_length=64)),
                ('location', models.CharField(max_length=255)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('canceled', 'Canceled')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_enrollments', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='events.event')),
            ],
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['starts_at'], name='events_even_starts__b01102_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['language'], name='events_even_languag_67ce95_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['location'], name='events_even_locatio_0ae1f4_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['created_by'], name='events_even_created_95418c_idx'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='event_ends_after_starts'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['event', 'status'], name='events_enro_event_i_3b2aa3_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'enrolled')), fields=('event', 'seeker'), name='enrollment_one_active_per_event_seeker'),
        ),
    ]
