# Generated by Django 5.2.13 on 2026-04-16 00:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='event',
            name='events_even_created_95418c_idx',
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['seeker', 'status'], name='events_enro_seeker__f3e9b0_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['created_by', 'starts_at'], name='events_even_created_809bd1_idx'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__isnull', True), ('capacity__gte', 1), _connector='OR'), name='event_capacity_null_or_at_least_one'),
        ),
    ]
